[alembic]
script_location = alembic
file_template = %%(rev)s_%%(slug)s
prepend_sys_path = .
version_path_separator = os

# Set this from env in alembic/env.py instead of hardcoding here
sqlalchemy.url = sqlite+aiosqlite:///./helix_srop.db
